feat: leader profiles block
hlxsites/netcentric pull request #47
Opened 2022-11-22 12:24 UTC by buuhuu

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #37 

Test URLs:
- Before: https://main--netcentric--hlxsites.hlx.page/who-we-are
- After: https://37-leader-profiles--netcentric--hlxsites.hlx.page/who-we-are

2022-11-22 13:02 UTC, hannessolo commented
Can you link the page (in the before/after) where the leader block is meant to appear?

2022-11-22 13:20 UTC, mhaack commented
@hannessolo done.

2022-11-22 13:21 UTC, mhaack commented
@Buuhuu not sure if this is already read for review since you added us. Looks good, but people details don't show up. So I assume it is still work in progress.

2022-11-23 09:41 UTC, mhaack approved these changes

2022-11-23 10:39 UTC, hannessolo requested changes
LGTM except for cursor

2022-11-23 10:39 UTC, hannessolo commented on blocks/leader-profiles/leader-profiles.css
> +.leader-profiles>ul {
Can you set `cursor: pointer` so its visually indicated that you can click the cards?

2022-11-23 12:19 UTC, hannessolo approved these changes

2022-11-23 13:14 UTC, merged